-- =====================================================
-- MESSAGING AND STATISTICS TABLES
-- =====================================================
-- Migration 013: Add conversations, messages, and property_statistics tables

-- =====================================================
-- CONVERSATIONS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  buyer_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  buyer_unread_count INTEGER DEFAULT 0 CHECK (buyer_unread_count >= 0),
  seller_unread_count INTEGER DEFAULT 0 CHECK (seller_unread_count >= 0),
  last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Ensure unique conversation per property and buyer
  UNIQUE(property_id, buyer_id),

  -- Prevent self-conversations
  CHECK (buyer_id != seller_id)
);

-- Conversations indexes
CREATE INDEX IF NOT EXISTS idx_conversations_property ON conversations(property_id);
CREATE INDEX IF NOT EXISTS idx_conversations_buyer ON conversations(buyer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_seller ON conversations(seller_id);
CREATE INDEX IF NOT EXISTS idx_conversations_last_message ON conversations(last_message_at DESC);

COMMENT ON TABLE conversations IS 'Conversations between buyers and sellers about properties';
COMMENT ON COLUMN conversations.buyer_unread_count IS 'Number of unread messages for the buyer';
COMMENT ON COLUMN conversations.seller_unread_count IS 'Number of unread messages for the seller';

-- =====================================================
-- MESSAGES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
  sender_type TEXT NOT NULL CHECK (sender_type IN ('buyer', 'seller', 'ai')),
  content TEXT NOT NULL,
  is_ai_generated BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Messages indexes
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_created ON messages(created_at DESC);

COMMENT ON TABLE messages IS 'Messages within conversations';
COMMENT ON COLUMN messages.sender_type IS 'Type of sender: buyer, seller, or ai';
COMMENT ON COLUMN messages.is_ai_generated IS 'Whether this message was generated by AI';

-- =====================================================
-- PROPERTY STATISTICS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS property_statistics (
  property_id UUID PRIMARY KEY REFERENCES properties(id) ON DELETE CASCADE,
  total_views INTEGER DEFAULT 0 CHECK (total_views >= 0),
  unique_viewers INTEGER DEFAULT 0 CHECK (unique_viewers >= 0),
  favorites_count INTEGER DEFAULT 0 CHECK (favorites_count >= 0),
  views_last_7_days INTEGER DEFAULT 0 CHECK (views_last_7_days >= 0),
  views_last_30_days INTEGER DEFAULT 0 CHECK (views_last_30_days >= 0),
  feedback_count INTEGER DEFAULT 0 CHECK (feedback_count >= 0),
  avg_rating DECIMAL(3,2) CHECK (avg_rating IS NULL OR (avg_rating >= 0 AND avg_rating <= 5)),
  avg_price_rating DECIMAL(3,2) CHECK (avg_price_rating IS NULL OR (avg_price_rating >= 0 AND avg_price_rating <= 5)),
  avg_location_rating DECIMAL(3,2) CHECK (avg_location_rating IS NULL OR (avg_location_rating >= 0 AND avg_location_rating <= 5)),
  avg_condition_rating DECIMAL(3,2) CHECK (avg_condition_rating IS NULL OR (avg_condition_rating >= 0 AND avg_condition_rating <= 5)),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Property statistics indexes
CREATE INDEX IF NOT EXISTS idx_property_statistics_views ON property_statistics(total_views DESC);
CREATE INDEX IF NOT EXISTS idx_property_statistics_favorites ON property_statistics(favorites_count DESC);

COMMENT ON TABLE property_statistics IS 'Statistics and metrics for properties';
COMMENT ON COLUMN property_statistics.total_views IS 'Total number of views for this property';
COMMENT ON COLUMN property_statistics.unique_viewers IS 'Number of unique users who viewed this property';

-- =====================================================
-- TRIGGERS FOR AUTOMATIC STATISTICS
-- =====================================================

-- Function to update conversation last_message_at
CREATE OR REPLACE FUNCTION update_conversation_last_message()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE conversations
  SET last_message_at = NEW.created_at
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update last_message_at when new message is inserted
CREATE TRIGGER trigger_update_conversation_last_message
  AFTER INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION update_conversation_last_message();

-- Function to automatically create property statistics entry
CREATE OR REPLACE FUNCTION create_property_statistics()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO property_statistics (property_id)
  VALUES (NEW.id)
  ON CONFLICT (property_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to create statistics entry when new property is created
CREATE TRIGGER trigger_create_property_statistics
  AFTER INSERT ON properties
  FOR EACH ROW
  EXECUTE FUNCTION create_property_statistics();

-- Create statistics entries for existing properties
INSERT INTO property_statistics (property_id)
SELECT id FROM properties
WHERE id NOT IN (SELECT property_id FROM property_statistics)
ON CONFLICT (property_id) DO NOTHING;

-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

-- Enable RLS
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_statistics ENABLE ROW LEVEL SECURITY;

-- Conversations policies
CREATE POLICY "Users can view conversations they participate in"
  ON conversations FOR SELECT
  TO authenticated
  USING (
    buyer_id IN (SELECT id FROM user_profiles WHERE user_id = public.current_user_id()) OR
    seller_id IN (SELECT id FROM user_profiles WHERE user_id = public.current_user_id())
  );

-- Messages policies
CREATE POLICY "Users can view messages in their conversations"
  ON messages FOR SELECT
  TO authenticated
  USING (
    conversation_id IN (
      SELECT id FROM conversations WHERE
        buyer_id IN (SELECT id FROM user_profiles WHERE user_id = public.current_user_id()) OR
        seller_id IN (SELECT id FROM user_profiles WHERE user_id = public.current_user_id())
    )
  );

CREATE POLICY "Users can insert messages in their conversations"
  ON messages FOR INSERT
  TO authenticated
  WITH CHECK (
    conversation_id IN (
      SELECT id FROM conversations WHERE
        buyer_id IN (SELECT id FROM user_profiles WHERE user_id = public.current_user_id()) OR
        seller_id IN (SELECT id FROM user_profiles WHERE user_id = public.current_user_id())
    )
  );

-- Property statistics policies
CREATE POLICY "Anyone can view property statistics"
  ON property_statistics FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Property owners can update their statistics"
  ON property_statistics FOR UPDATE
  TO authenticated
  USING (
    property_id IN (SELECT id FROM properties WHERE user_id = public.current_user_id())
  );
